# Generated by Django 4.1.7 on 2023-04-09 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_person_employee_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teachingassisting",
            options={"ordering": ["-semester", "person"]},
        ),
    ]
