# Generated by Django 4.1.7 on 2023-04-09 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_teachingassisting_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrolling",
            options={"ordering": ["-semester", "person"]},
        ),
        migrations.AlterModelOptions(
            name="instruction",
            options={"ordering": ["-semester", "person"]},
        ),
    ]
