# Generated by Django 4.1.7 on 2023-04-09 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_teachingassisting_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instruction",
            options={"ordering": ["person", "-semester"]},
        ),
        migrations.AlterModelOptions(
            name="teachingassisting",
            options={"ordering": ["person", "-semester"]},
        ),
    ]
