# Generated by Django 4.1.7 on 2023-04-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_filematerial_urlmaterial_session_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="solutions",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="solutions",
                to="core.filematerial",
            ),
        ),
    ]
