# Generated by Django 4.1.7 on 2023-04-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_assignment_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="questions",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="questions",
                to="core.filematerial",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="solutions",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="solutions",
                to="core.filematerial",
            ),
            preserve_default=False,
        ),
    ]
