# Generated by Django 4.1.7 on 2023-04-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_assignment_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="questions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="questions",
                to="core.filematerial",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="solutions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="solutions",
                to="core.filematerial",
            ),
        ),
        migrations.AlterField(
            model_name="enrolling",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructors",
                to="core.semester",
            ),
        ),
        migrations.AlterField(
            model_name="teachingassisting",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_assistant",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="teachingassisting",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_assistants",
                to="core.semester",
            ),
        ),
    ]
