name: jabrekh_website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest   
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_SECRET }}
          port: ${{ secrets.VPS_SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
              cd ${{ secrets.PROJECT_PATH }}
              git pull origin main
              make down
              docker image prune -a -f
              make up
              make collect_static
              make migrate
